BackEnd/My_Django_Stuff/learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name= 'basic_app'

urlpatterns=[
    url('register/',views.register,name='register'),
    url('user_login/',views.user_login,name='user_login'),
]

BackEnd/My_Django_Stuff/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
]

BackEnd/My_Django_Stuff/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    # OneToOneField relationship:a class to add information that default User doesn't have
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # user has one to one relationship with User

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

BackEnd/My_Django_Stuff/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

BackEnd/My_Django_Stuff/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm 
#modules for login & logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'basic_app\\index.html')

#login is required before user can logout,line @ must be followed by line def
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            #grab things in user_form
            user = user_form.save()
            user.set_password(user.password) #hashing the password
            user.save() #save the hashed password to the database

            #grab things in profile_form
            profile = profile_form.save(commit=False)
            #do not save yet, may get error when overwrite user when saving profile
            profile.user = user
            # proile.user = profile_form.user = UserProfileInfoForm.user = UserProfileInfo.user(inherite)
            # user = user_form =UserForm
            # this equation stands for the one to one relationship in models

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic'] #dictionary of the files user uploaded in request

            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})    

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                # if POST is authenticated and active, return to the homepage
            
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("LOGIN FAILED!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'basic_app/login.html',{})

BackEnd/My_Django_Stuff/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">ADMIN <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'basic_app:register' %}">REGISTER</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class='nav-link' href="{% url 'logout' %}">LOGOUT</a></li>
                {% else %}
                    <li class="nav-item">
                        <a class='nav-link' href="{% url 'basic_app:user_login' %}">LOGIN</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <div class='container'>
            {% block body_block %}
            {% endblock %}  
        </div>
    </body>
</html>

BackEnd/My_Django_Stuff/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>
{% endblock %}  

BackEnd/My_Django_Stuff/learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        <!-- call request to URL and then POST -->
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password: </label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>
</div>
{% endblock %}  

BackEnd/My_Django_Stuff/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
    {%if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
        
        <form enctype="multipart/form-data" method="POST">
            <!-- enctype="multipart/form-data":ensure the uploading of images works -->
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <!-- linked with view -->
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>
{% endblock %}  