BackEnd/My_Django_Stuff/class_based_view/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url('',views.SchoolListView.as_view(),name='list'),    
    url('<int:school_pk>/',views.SchoolDetailView.as_view(),name='detail'),
]

BackEnd/My_Django_Stuff/class_based_view/class_based_view/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app',include('basic_app.urls')),
]

BackEnd/My_Django_Stuff/class_based_view/basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=300)
    principal = models.CharField(max_length=300)
    location = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=300)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)
    # related name: relate School to student

    def __str__(self):
        return self.name

BackEnd/My_Django_Stuff/class_based_view/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from django.http import HttpResponse
from . import models

# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!' 
        return context

class SchoolListView(ListView):
    model = models.School
    # for ListView, it will automatically create a context dictionary 'school_list', which could be injected in HTML
    context_object_name = 'schools'
    # we could create our own context dictionary

class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'basic_app/school_detail.html'
    # for DetailView, it will automatically create a context dictionary 'school', which could be injected in HTML
    context_object_name = 'school_detail'

BackEnd/My_Django_Stuff/class_based_view/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
            <!-- list is the name of a urlpatterns -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">ADMIN <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"></a>
                </li>
              </ul>
            </div>
          </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

BackEnd/My_Django_Stuff/class_based_view/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<div class='jumbotron'>
    <h1>Welcome to the School Detail Page!</h1>
    <h2>School details:</h2>
    <p>NAME: {{school_detail.name}}</p>
    <p>PRINCIPAL: {{school_detail.principal}}</p>
    <p>LOCATION: {{school_detail.location}}</p>
    <h3>Students:</h3>

    {% for student in student_detail.students.all %}
    <!-- students represent models.class Student.School.related name -->
        <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}


</div>

{% endblock %}

BackEnd/My_Django_Stuff/class_based_view/basic_app/templates/basic_app/school_list.html
{%extends "basic_app/basic_app_base.html"%}

{%block body_block%}
    <h1>Welcome to a list of all schools!</h1>
        <ol>
            <!-- {%for school in school_list%} -->
            <!-- school_list is a context dictionary automatically generated by ListView -->
            <!-- {% endfor %} -->
            {%for school in schools%}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
            <!-- ID is a automatic generated primary key for list view -->
            {%endfor%}
        </ol>
{%endblock%}

BackEnd/My_Django_Stuff/class_based_view/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
            <!-- list is the name of a urlpatterns -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">ADMIN <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"></a>
                </li>
              </ul>
            </div>
          </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

BackEnd/My_Django_Stuff/class_based_view/templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <h1>WELCOME TO HOME PATG!</h1>
    <h2>{{ injectme }}</h2>
{% endblock %}